[package]
name = "viam"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"]}
futures = {version = "0.3", default-features = false, features = ["alloc"]}
prost = "0.9"
prost-types = "0.9"
futures-core = "0.3"
futures-util = "0.3"
tower = { version = "0.4" }
http = "0.2"
tokio = {version = "1.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"]}
tokio-stream = {version = "0.1", features = ["net"]}
tonic = {version = "0.6.2",features = ["tls", "compression", "tls-roots"]}
async-stream = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
tokio-rustls = { version = "0.23.3"}
webpki-roots = "0.21.1"



[build-dependencies]
tonic-build = {version = "0.6.2",features = ["prost", "compression"]}
