[package]
edition = "2021"
name = "example"
version = "0.0.1"

[[bin]]
name = "test-dialdirect"
path = "src/dialdirect/main.rs"

[dependencies]
viam = {path = "../"}
anyhow = { version = "1.0", features = ["backtrace"]}
tokio = { version = "1.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }
tonic = {version = "0.6.2",features = ["tls", "compression", "tls-roots"]}
